import type { LoomPreset, LoomSettings } from './types.js';

export const LOOM_VERSION = '1.0.29';
export const LOOM_SCHEMA_VERSION = '1';
export const GRAND_CONTINUITY_ATLAS_PRESET_ID = 'grand_continuity_atlas';
export const SLIM_SCENE_PRESET_ID = 'slim_scene_loom';
export const STORAGE_KEYS = {
  settings: 'settings.json',
  presets: 'presets.json',
  trackerStates: 'tracker-states.json',
} as const;

const now = '2026-01-01T00:00:00.000Z';

export const defaultSettings: LoomSettings = {
  enabled: true,
  activePresetId: GRAND_CONTINUITY_ATLAS_PRESET_ID,
  autoGenerate: false,
  useDefaultConnectionFallback: true,
  stripTrackerBlocksFromMessages: false,
  showFloatingButton: false,
  showMessageButtons: true,
  debugMode: false,
  promptInjectionEnabled: false,
  showChatHudLauncher: true,
  hudDefaultView: 'full',
  renderInMessages: false,
  messageCardPlacement: 'top',
  cardDensity: 'compact',
  trackerHistoryLimit: 20,
  sidecarGenerationTimeoutMs: 180000,
  useSafeRenderer: false,
  customTemplateMode: 'trusted_layout',
  promptInjectionMode: 'latest_plus_history',
  promptInjectionTrackerLimit: 5,
  promptInjectionTokenBudget: 700,
  trackerGenerationHistoryLimit: 5,
  promptInjectionIncludeAppearance: true,
  promptInjectionIncludeRules: true,
  promptInjectionIncludeNextTurn: true,
};

// 0. Grand Continuity Atlas (new default for new installs and resets)
export const grandContinuityAtlasPreset: LoomPreset = {
  id: GRAND_CONTINUITY_ATLAS_PRESET_ID,
  name: 'Grand Continuity Atlas',
  version: '1.0.25',
  description: 'A detailed, visually polished continuity atlas for rich roleplay scenes, character appearance, relationships, world state, and fragile details.',
  origin: 'built-in',
  templateEngine: 'handlebars_compat',
  sourceFormat: 'loom',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneIdentity', 'narrativeDelta', 'characters', 'worldState', 'nextTurnGuidance'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneIdentity: {
        type: 'object',
        properties: {
          title: { type: 'string', default: '' },
          location: { type: 'string', default: '' },
          subLocation: { type: 'string', default: '' },
          time: { type: 'string', default: '' },
          date: { type: 'string', default: '' },
          weather: { type: 'string', default: '' },
          lighting: { type: 'string', default: '' },
          privacy: { type: 'string', default: '' },
          pacing: { type: 'string', default: '' },
          tension: { type: 'string', default: '' },
          mood: { type: 'string', default: '' },
          sensoryAtmosphere: { type: 'string', default: '' },
          atmosphere: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
        },
      },
      narrativeDelta: {
        type: 'object',
        properties: {
          summary: { type: 'string', default: '' },
          whatChanged: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
          immediateConsequences: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
          unresolvedBeats: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
          continuityWarnings: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
        },
      },
      characters: {
        type: 'array',
        maxItems: 8,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            role: { type: 'string', default: '' },
            presence: { type: 'string', default: '' },
            location: { type: 'string', default: '' },
            currentAction: { type: 'string', default: '' },
            appearance: {
              type: 'object',
              properties: {
                overview: { type: 'string', default: '' },
                face: { type: 'string', default: '' },
                hair: { type: 'string', default: '' },
                eyes: { type: 'string', default: '' },
                bodyBuild: { type: 'string', default: '' },
                clothing: { type: 'string', default: '' },
                posture: { type: 'string', default: '' },
                voice: { type: 'string', default: '' },
                scent: { type: 'string', default: '' },
                visibleCondition: { type: 'string', default: '' },
              },
            },
            state: {
              type: 'object',
              properties: {
                emotion: { type: 'string', default: '' },
                hiddenTension: { type: 'string', default: '' },
                injuries: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
                fatigue: { type: 'string', default: '' },
                goals: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
                knowledge: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
                secrets: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
                boundaries: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
              },
            },
            relationshipToUser: {
              type: 'object',
              properties: {
                label: { type: 'string', default: '' },
                trust: { type: 'integer', default: 0 },
                warmth: { type: 'integer', default: 0 },
                attraction: { type: 'integer', default: 0 },
                irritation: { type: 'integer', default: 0 },
                fear: { type: 'integer', default: 0 },
                leverage: { type: 'string', default: '' },
                recentShift: { type: 'string', default: '' },
              },
            },
            props: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
            inventory: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
            changesThisTurn: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
          },
        },
      },
      relationships: {
        type: 'array',
        maxItems: 10,
        default: [],
        items: {
          type: 'object',
          properties: {
            parties: { type: 'string', default: '' },
            trust: { type: 'string', default: '' },
            warmth: { type: 'string', default: '' },
            attraction: { type: 'string', default: '' },
            irritation: { type: 'string', default: '' },
            fear: { type: 'string', default: '' },
            promises: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
            conflicts: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
            debts: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
            recentShift: { type: 'string', default: '' },
          },
        },
      },
      worldState: {
        type: 'object',
        properties: {
          importantObjects: { type: 'array', maxItems: 10, default: [], items: { type: 'string' } },
          hazards: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
          activeThreads: { type: 'array', maxItems: 10, default: [], items: { type: 'string' } },
          loreFacts: { type: 'array', maxItems: 10, default: [], items: { type: 'string' } },
          constraints: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
          timelineAnchors: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
          sceneRules: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
          contradictions: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
        },
      },
      nextTurnGuidance: {
        type: 'object',
        properties: {
          likelyFocus: { type: 'string', default: '' },
          fragileDetails: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
          doNotForget: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
          avoidInventing: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
        },
      },
    },
  },
  htmlTemplate: [
    '<section class="sotl-atlas sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '<style>',
    '.sotl-atlas{font-family:var(--lv-font-sans,Inter,ui-sans-serif,system-ui,sans-serif);color:var(--lumiverse-text,var(--lv-text,#eef2ff));background:linear-gradient(145deg,rgba(12,16,24,.96),rgba(21,27,38,.94));border:1px solid rgba(130,150,190,.3);border-radius:14px;padding:14px;box-shadow:0 16px 44px rgba(0,0,0,.38);display:grid;gap:12px;overflow:hidden}',
    '.sotl-atlas *{box-sizing:border-box}',
    '.sotl-atlas__head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:start;border-bottom:1px solid rgba(255,255,255,.11);padding-bottom:10px}',
    '.sotl-atlas__eyebrow{font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#9fb7ff;font-weight:800}',
    '.sotl-atlas h3{margin:2px 0 0;font-size:18px;line-height:1.15;color:#fff}',
    '.sotl-atlas__mood{display:inline-flex;align-items:center;border:1px solid rgba(159,183,255,.35);background:rgba(95,122,255,.14);border-radius:999px;padding:4px 9px;font-size:11px;color:#dbe5ff;white-space:nowrap}',
    '.sotl-atlas__chips{display:flex;flex-wrap:wrap;gap:6px}',
    '.sotl-atlas__chip{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.055);border-radius:7px;padding:5px 7px;font-size:11px;color:#d8deea;line-height:1.25}',
    '.sotl-atlas__delta{font-size:13px;line-height:1.5;color:#f4f7ff;margin:0;padding:10px;border-radius:10px;background:rgba(255,255,255,.06);border-left:3px solid #8fb0ff}',
    '.sotl-atlas__grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}',
    '.sotl-atlas__panel{border:1px solid rgba(255,255,255,.11);background:rgba(255,255,255,.045);border-radius:10px;padding:10px;min-width:0}',
    '.sotl-atlas__panel h4{margin:0 0 7px;font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#9fb7ff}',
    '.sotl-atlas__list{margin:0;padding-left:16px;font-size:12px;line-height:1.45;color:#e1e7f2}',
    '.sotl-atlas__cast{display:grid;gap:9px}',
    '.sotl-atlas__person{border:1px solid rgba(159,183,255,.18);background:rgba(159,183,255,.06);border-radius:10px;padding:10px;display:grid;gap:8px}',
    '.sotl-atlas__person-head{display:flex;align-items:center;justify-content:space-between;gap:8px}',
    '.sotl-atlas__person h5{margin:0;font-size:14px;color:#fff}.sotl-atlas__role{font-size:11px;color:#b6c2d8}',
    '.sotl-atlas__kv{display:grid;grid-template-columns:82px minmax(0,1fr);gap:4px 8px;font-size:12px;line-height:1.38}.sotl-atlas__kv b{color:#9fb7ff;font-size:10px;text-transform:uppercase;letter-spacing:.05em}.sotl-atlas__kv span{min-width:0;overflow-wrap:anywhere}',
    '.sotl-atlas__meters{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:5px}.sotl-atlas__meter{background:rgba(0,0,0,.18);border-radius:7px;padding:5px;text-align:center}.sotl-atlas__meter b{display:block;font-size:9px;color:#9fb7ff;text-transform:uppercase}.sotl-atlas__meter span{font-size:12px;color:#fff;font-weight:800}',
    '@media(max-width:560px){.sotl-atlas{padding:11px;border-radius:10px}.sotl-atlas__head{grid-template-columns:1fr}.sotl-atlas__grid{grid-template-columns:1fr}.sotl-atlas__meters{grid-template-columns:repeat(3,minmax(0,1fr))}.sotl-atlas__kv{grid-template-columns:72px minmax(0,1fr)}}',
    '</style>',
    '<header class="sotl-atlas__head">',
    '  <div><div class="sotl-atlas__eyebrow">Grand Continuity Atlas</div><h3>{{sceneIdentity.title}}</h3></div>',
    '  <span class="sotl-atlas__mood">{{sceneIdentity.mood}}</span>',
    '</header>',
    '<div class="sotl-atlas__chips">',
    '  <span class="sotl-atlas__chip">Location: {{sceneIdentity.location}}{{#if sceneIdentity.subLocation}} / {{sceneIdentity.subLocation}}{{/if}}</span>',
    '  <span class="sotl-atlas__chip">Time: {{sceneIdentity.time}}</span>',
    '  <span class="sotl-atlas__chip">Weather: {{sceneIdentity.weather}}</span>',
    '  <span class="sotl-atlas__chip">Light: {{sceneIdentity.lighting}}</span>',
    '  <span class="sotl-atlas__chip">Privacy: {{sceneIdentity.privacy}}</span>',
    '  <span class="sotl-atlas__chip">Tension: {{sceneIdentity.tension}}</span>',
    '</div>',
    '<p class="sotl-atlas__delta">{{narrativeDelta.summary}}</p>',
    '<section class="sotl-atlas__cast">',
    '{{#each characters}}',
    '  <article class="sotl-atlas__person">',
    '    <div class="sotl-atlas__person-head"><div><h5>{{name}}</h5><div class="sotl-atlas__role">{{role}} - {{presence}} - {{location}}</div></div><span class="sotl-atlas__chip">{{state.emotion}}</span></div>',
    '    <div class="sotl-atlas__kv">',
    '      <b>Face</b><span>{{appearance.face}}</span><b>Hair</b><span>{{appearance.hair}}</span><b>Eyes</b><span>{{appearance.eyes}}</span><b>Build</b><span>{{appearance.bodyBuild}}</span><b>Clothes</b><span>{{appearance.clothing}}</span><b>Posture</b><span>{{appearance.posture}}</span><b>Voice</b><span>{{appearance.voice}}</span><b>Condition</b><span>{{appearance.visibleCondition}}</span>',
    '    </div>',
    '    <div class="sotl-atlas__meters"><div class="sotl-atlas__meter"><b>Trust</b><span>{{relationshipToUser.trust}}</span></div><div class="sotl-atlas__meter"><b>Warmth</b><span>{{relationshipToUser.warmth}}</span></div><div class="sotl-atlas__meter"><b>Attract</b><span>{{relationshipToUser.attraction}}</span></div><div class="sotl-atlas__meter"><b>Irrit.</b><span>{{relationshipToUser.irritation}}</span></div><div class="sotl-atlas__meter"><b>Fear</b><span>{{relationshipToUser.fear}}</span></div></div>',
    '    <div class="sotl-atlas__grid">',
    '      <div class="sotl-atlas__panel"><h4>Intent and Knowledge</h4><ul class="sotl-atlas__list">{{#each state.goals}}<li>{{this}}</li>{{/each}}{{#each state.knowledge}}<li>{{this}}</li>{{/each}}</ul></div>',
    '      <div class="sotl-atlas__panel"><h4>Props and Changes</h4><ul class="sotl-atlas__list">{{#each props}}<li>{{this}}</li>{{/each}}{{#each inventory}}<li>{{this}}</li>{{/each}}{{#each changesThisTurn}}<li>{{this}}</li>{{/each}}</ul></div>',
    '    </div>',
    '  </article>',
    '{{/each}}',
    '</section>',
    '<section class="sotl-atlas__grid">',
    '  <div class="sotl-atlas__panel"><h4>World State</h4><ul class="sotl-atlas__list">{{#each worldState.importantObjects}}<li>{{this}}</li>{{/each}}{{#each worldState.hazards}}<li>{{this}}</li>{{/each}}{{#each worldState.activeThreads}}<li>{{this}}</li>{{/each}}{{#each worldState.loreFacts}}<li>{{this}}</li>{{/each}}</ul></div>',
    '  <div class="sotl-atlas__panel"><h4>Next Turn Guidance</h4><p style="font-size:12px;line-height:1.45;margin:0 0 6px;color:#f4f7ff;">{{nextTurnGuidance.likelyFocus}}</p><ul class="sotl-atlas__list">{{#each nextTurnGuidance.fragileDetails}}<li>{{this}}</li>{{/each}}{{#each nextTurnGuidance.doNotForget}}<li>{{this}}</li>{{/each}}{{#each nextTurnGuidance.avoidInventing}}<li>{{this}}</li>{{/each}}</ul></div>',
    '</section>',
    '{{#if relationships}}<details class="sotl-card-details" open><summary>Relationship Ledger</summary><ul class="sotl-atlas__list">{{#each relationships}}<li><strong>{{parties}}</strong>: trust {{trust}}, warmth {{warmth}}, attraction {{attraction}}, irritation {{irritation}}, fear {{fear}}. {{recentShift}}</li>{{/each}}</ul></details>{{/if}}',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom: Grand Continuity Atlas, a high-detail continuity tracker for AI roleplay.',
    'Return raw JSON only. Do not use markdown fences, XML tags, comments, prose outside JSON, or explanations.',
    'Use the Grand Continuity Atlas schema exactly. Include every required top-level object.',
    'Target roughly 2200-2800 JSON tokens when the scene has enough material. Do not pad with invented facts; if information is unknown, use concise empty strings or empty arrays.',
    'Preserve stable facts from the previous tracker unless the latest assistant message clearly changes them.',
    'Track character appearance with unusually strong continuity: face, hair, eyes, build, clothing, posture, voice, scent, visible condition, injuries, fatigue, emotional state, hidden tension, goals, knowledge, secrets, boundaries, props, inventory, and changes this turn.',
    'Track relationships as state, not vibes only: trust, warmth, attraction, irritation, fear, leverage, promises, conflicts, debts, and recent shifts.',
    'Track world state: important objects, hazards, active threads, lore facts, constraints, timeline anchors, scene rules, contradictions, and continuity warnings.',
    'Use 0-100 integers for relationshipToUser meter values. Keep arrays within maxItems. Prefer specific compact phrases over vague labels.',
    'The latest assistant message is authoritative for what just happened; the previous tracker is authoritative for stable continuity that was not contradicted.',
  ].join('\n'),
  injectionTemplate: '[Grand Continuity Atlas]\n{{compactSummary}}',
  maxInjectionTokens: 900,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'expanded',
    theme: 'glass',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom', 'atlas'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneIdentity: {
      title: 'Kitchen Introduction Under Stormlight',
      location: 'Ward House',
      subLocation: 'Kitchen threshold',
      time: '5:35 PM',
      date: '2024-07-12',
      weather: 'hot, stagnant, humid late afternoon with thunder building outside',
      lighting: 'low afternoon sun through windows and warm kitchen overheads',
      privacy: 'semi-private; Bridget and Diane can observe Josh',
      pacing: 'slow social pressure with physical discomfort',
      tension: 'strained, awkward, mildly buzzed',
      mood: 'tense but domestic',
      sensoryAtmosphere: 'heavy summer heat, tile underfoot, old wood, glass clinks, storm scent near the door',
      atmosphere: ['heavy standing heat', 'old kitchen wood', 'wet storm smell near the threshold'],
    },
    narrativeDelta: {
      summary: 'Josh enters the kitchen after Diane and makes a clumsy offer to leave while Bridget observes from the counter with wine in hand.',
      whatChanged: ['Josh has arrived in the kitchen.', 'Bridget is confirmed present and watching.', 'Marcus remains absent.'],
      immediateConsequences: ['Josh must navigate Bridget and Diane while physically strained.'],
      unresolvedBeats: ['Why Marcus is absent.', 'Whether Josh can move upstairs safely.'],
      continuityWarnings: ['Do not forget Josh is dealing with a severe right-leg cramp.'],
    },
    characters: [
      {
        name: 'Josh',
        role: 'visitor',
        presence: 'active in scene',
        location: 'kitchen threshold',
        currentAction: 'offering to leave despite pain',
        appearance: {
          overview: 'strained, overheated, trying to look composed',
          face: 'tight around the mouth from pain',
          hair: 'slightly mussed from the humid house',
          eyes: 'watchful and embarrassed',
          bodyBuild: 'adult build, currently favoring one leg',
          clothing: 'casual travel clothes, rumpled from the heat',
          posture: 'weight shifted off the right leg',
          voice: 'polite but strained',
          scent: 'warm skin and storm-damp air',
          visibleCondition: 'severe right-leg cramp limiting movement',
        },
        state: {
          emotion: 'awkward and tense',
          hiddenTension: 'does not want to look helpless in front of Bridget',
          injuries: ['severe right-leg cramp'],
          fatigue: 'physically strained',
          goals: ['avoid imposing', 'reach Marcus or learn where he is'],
          knowledge: ['Marcus is absent', 'Diane and Bridget are watching him'],
          secrets: [],
          boundaries: ['should not sprint or climb quickly while cramped'],
        },
        relationshipToUser: {
          label: 'player viewpoint',
          trust: 50,
          warmth: 45,
          attraction: 0,
          irritation: 15,
          fear: 10,
          leverage: 'none established',
          recentShift: 'more vulnerable after visible pain',
        },
        props: [],
        inventory: [],
        changesThisTurn: ['entered kitchen', 'showed strain from leg cramp'],
      },
      {
        name: 'Bridget Hanley',
        role: 'aunt and drinker of wine',
        presence: 'active observer',
        location: 'leaning near the kitchen counter',
        currentAction: 'watching Josh with sharp curiosity',
        appearance: {
          overview: 'composed, amused, slightly buzzed',
          face: 'sharp-eyed with a faintly assessing expression',
          hair: 'neat enough but casual for the house',
          eyes: 'focused on Josh',
          bodyBuild: 'relaxed adult posture',
          clothing: 'house casuals with a folded towel in hand',
          posture: 'leaning at the counter, glass nearby',
          voice: 'dry and curious',
          scent: 'wine and warm kitchen air',
          visibleCondition: 'mildly buzzed but observant',
        },
        state: {
          emotion: 'curious and amused',
          hiddenTension: 'testing Josh socially',
          injuries: [],
          fatigue: 'none obvious',
          goals: ['understand who Josh is', 'watch Diane handle him'],
          knowledge: ['Josh is struggling physically', 'Marcus is not here'],
          secrets: [],
          boundaries: ['keeps social control through teasing observation'],
        },
        relationshipToUser: {
          label: 'new acquaintance',
          trust: 30,
          warmth: 35,
          attraction: 0,
          irritation: 20,
          fear: 0,
          leverage: 'social confidence in her own kitchen',
          recentShift: 'became more interested after seeing Josh struggle',
        },
        props: ['wine glass', 'folded towel'],
        inventory: [],
        changesThisTurn: ['identified as present and observing Josh'],
      },
    ],
    relationships: [
      {
        parties: 'Josh and Bridget',
        trust: 'low but open',
        warmth: 'testing curiosity',
        attraction: 'not established',
        irritation: 'minor awkwardness',
        fear: 'none',
        promises: [],
        conflicts: ['Josh may be judged for arriving while Marcus is absent'],
        debts: [],
        recentShift: 'Bridget has begun evaluating Josh directly.',
      },
    ],
    worldState: {
      importantObjects: ['wine glass on the counter', 'kitchen threshold', 'stair path toward Marcus room'],
      hazards: ['Josh right-leg cramp', 'hot stagnant room', 'social scrutiny'],
      activeThreads: ['Marcus absence', 'Josh trying to reach upstairs', 'Bridget assessing Josh'],
      loreFacts: ['Ward House kitchen is occupied by Diane and Bridget.'],
      constraints: ['Josh movement is impaired.', 'Marcus should not suddenly appear without setup.'],
      timelineAnchors: ['Josh arrived after Diane entered the kitchen.'],
      sceneRules: ['Domestic realism and social tension matter more than action.'],
      contradictions: [],
    },
    nextTurnGuidance: {
      likelyFocus: 'Josh needs to answer Bridget or Diane while managing the leg cramp.',
      fragileDetails: ['Josh is at the threshold, not upstairs.', 'Bridget has wine and is watching closely.'],
      doNotForget: ['Marcus is absent.', 'Diane is present.', 'The right-leg cramp is severe.'],
      avoidInventing: ['Do not invent Marcus location yet.', 'Do not resolve the cramp instantly.'],
    },
  },
  createdAt: now,
  updatedAt: now,
};

// 1. Micro Loom Preset
export const microLoomPreset: LoomPreset = {
  id: 'micro_loom',
  name: 'Micro Loom',
  version: '1.0.4',
  description: 'Smallest, fastest tracker. Best for low token usage and fast models.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      cast: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      activeThread: { type: 'string', default: '' },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">Micro Loom</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{mood}}</span>',
    '  </header>',
    '  <dl class="sotl-grid">',
    '    <div class="sotl-grid-item"><dt>Location</dt><dd>{{location}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Time</dt><dd>{{time}}</dd></div>',
    '  </dl>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  <details class="sotl-card-details" open><summary>Cast Present</summary><ul class="sotl-anchors-list">{{#each cast}}<li>{{.}}</li>{{/each}}</ul></details>',
    '  {{#if activeThread}}<details class="sotl-card-details" open><summary>Active Thread</summary><p class="sotl-thread-desc">{{activeThread}}</p></details>{{/if}}',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, a micro-sized continuity tracker for an AI roleplay chat.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Micro Loom schema exactly.',
    'Preserve stable facts from the previous tracker unless the latest assistant message clearly changes them.',
    'Only update what changed this turn. Do not invent missing details.',
    'Use empty strings and [] for unknowns.',
    'Keep cast array under 4 items.',
  ].join('\n'),
  injectionTemplate: '[Micro Loom]\n{{compactSummary}}',
  maxInjectionTokens: 150,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'compact',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'Quick word in the foyer',
    location: 'Foyer',
    time: 'Late evening',
    mood: 'tense',
    delta: 'Mira entered quietly without shaking off her wet coat.',
    cast: ['Mira', 'Josh'],
    activeThread: 'Learn what Mira is hiding.',
  },
  createdAt: now,
  updatedAt: now,
};

// 2. Slim Scene Loom (Polished current preset)
export const slimSceneSampleData: Record<string, unknown> = {
  schemaVersion: LOOM_SCHEMA_VERSION,
  sceneTitle: 'A quiet turn in the old hall',
  location: 'Lantern Hall',
  time: 'Late evening',
  mood: 'watchful',
  delta: 'Mira noticed the sealed letter and did not comment on it.',
  showCast: true,
  cast: [
    {
      name: 'Mira',
      role: 'barkeep',
      position: 'behind the counter',
      outfit: 'rolled sleeves, dark apron',
      emotion: 'guarded',
      inventory: ['sealed letter'],
    },
  ],
  showInventory: true,
  inventory: ['sealed letter', 'brass key'],
  showThreads: true,
  activeThread: 'Find out who left the letter.',
  anchors: ['The cellar door is locked.', 'Rain is getting heavier outside.'],
  avoidNext: ['Do not reveal the letter contents yet.'],
};

export const slimScenePreset: LoomPreset = {
  id: SLIM_SCENE_PRESET_ID,
  name: 'Slim Scene Loom',
  version: '1.0.4',
  description: 'A low-token continuity tracker for location, cast, mood, inventory, deltas, and active story anchors.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      showCast: { type: 'boolean', default: false },
      cast: {
        type: 'array',
        maxItems: 6,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            role: { type: 'string', default: '' },
            position: { type: 'string', default: '' },
            outfit: { type: 'string', default: '' },
            emotion: { type: 'string', default: '' },
            inventory: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
          },
        },
      },
      showInventory: { type: 'boolean', default: false },
      inventory: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
      showThreads: { type: 'boolean', default: false },
      activeThread: { type: 'string', default: '' },
      anchors: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      avoidNext: { type: 'array', maxItems: 5, default: [], items: { type: 'string' } },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">State of the Loom</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{mood}}</span>',
    '  </header>',
    '  <dl class="sotl-grid">',
    '    <div class="sotl-grid-item"><dt>Location</dt><dd>{{location}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Time</dt><dd>{{time}}</dd></div>',
    '  </dl>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  {{#if showCast}}<div class="sotl-section sotl-cast-section"><h4>Cast Members</h4><div class="sotl-cast-grid">{{#each cast}}<article class="sotl-cast-chip"><strong>{{name}}</strong> <span class="sotl-cast-role">{{role}}</span> <span class="sotl-cast-pos">{{position}}</span> <em class="sotl-cast-emo">{{emotion}}</em></article>{{/each}}</div></div>{{/if}}',
    '  {{#if showInventory}}<details class="sotl-card-details" open><summary>Inventory Items</summary><ul class="sotl-inventory-list">{{#each inventory}}<li>{{.}}</li>{{/each}}</ul></details>{{/if}}',
    '  {{#if showThreads}}<details class="sotl-card-details" open><summary>Active Thread</summary><p class="sotl-thread-desc">{{activeThread}}</p></details>{{/if}}',
    '  <details class="sotl-card-details" open><summary>Scene Anchors</summary><ul class="sotl-anchors-list">{{#each anchors}}<li>{{.}}</li>{{/each}}</ul></details>',
    '  <details class="sotl-card-details"><summary>Avoid Next (Instructions)</summary><ul class="sotl-avoid-list">{{#each avoidNext}}<li>{{.}}</li>{{/each}}</ul></details>',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, a continuity tracker for an AI roleplay chat.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Slim Scene Loom schema exactly.',
    'Preserve stable facts from the previous tracker unless the latest assistant message clearly changes them.',
    'Only update what changed this turn. Do not invent missing details.',
    'Use empty strings, false, 0, and [] for unknowns.',
    'Keep arrays within their maxItems caps.',
  ].join('\n'),
  injectionTemplate: '[State of the Loom placeholder]\n{{compactSummary}}',
  maxInjectionTokens: 350,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'compact',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: slimSceneSampleData,
  createdAt: now,
  updatedAt: now,
};

// 3. Balanced Story Loom Preset
export const balancedStoryPreset: LoomPreset = {
  id: 'balanced_story_loom',
  name: 'Balanced Story Loom',
  version: '1.0.4',
  description: 'Medium-detail continuity tracker. Monitors environment, relationships, and cast pockets.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'environment', 'time', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      environment: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      cast: {
        type: 'array',
        maxItems: 5,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            role: { type: 'string', default: '' },
            position: { type: 'string', default: '' },
            outfit: { type: 'string', default: '' },
            emotion: { type: 'string', default: '' },
            pockets: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
          },
        },
      },
      relationships: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            parties: { type: 'string', default: '' },
            tone: { type: 'string', default: '' },
            details: { type: 'string', default: '' },
          },
        },
      },
      inventory: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      activeThread: { type: 'string', default: '' },
      anchors: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      contradictions: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">Balanced Story Loom</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{mood}}</span>',
    '  </header>',
    '  <p class="sotl-delta" style="font-size: 11px; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d)); margin-bottom: 8px;"><strong>Environment:</strong> {{environment}}</p>',
    '  <dl class="sotl-grid">',
    '    <div class="sotl-grid-item"><dt>Location</dt><dd>{{location}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Time</dt><dd>{{time}}</dd></div>',
    '  </dl>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  <div class="sotl-section sotl-cast-section">',
    '    <h4>Cast Details</h4>',
    '    <div class="sotl-cast-grid">',
    '      {{#each cast}}',
    '      <article class="sotl-cast-chip" style="flex-direction: column; align-items: flex-start; gap: 2px;">',
    '        <div><strong>{{name}}</strong> <span class="sotl-cast-role">({{role}})</span></div>',
    '        <div style="font-size: 11px;">📍 {{position}} • 👕 {{outfit}}</div>',
    '        <div style="font-size: 11px;">🎭 <em class="sotl-cast-emo">{{emotion}}</em></div>',
    '        {{#if pockets}}<div style="font-size: 10px; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d));">🎒 Pockets: {{pockets}}</div>{{/if}}',
    '      </article>',
    '      {{/each}}',
    '    </div>',
    '  </div>',
    '  {{#if relationships}}',
    '  <details class="sotl-card-details" open><summary>Relationships</summary>',
    '    <ul class="sotl-anchors-list">',
    '      {{#each relationships}}',
    '      <li><strong>{{parties}}</strong>: <em>{{tone}}</em> — {{details}}</li>',
    '      {{/each}}',
    '    </ul>',
    '  </details>',
    '  {{/if}}',
    '  <details class="sotl-card-details"><summary>Inventory Items</summary><ul class="sotl-inventory-list">{{#each inventory}}<li>{{.}}</li>{{/each}}</ul></details>',
    '  {{#if activeThread}}<details class="sotl-card-details" open><summary>Active Thread</summary><p class="sotl-thread-desc">{{activeThread}}</p></details>{{/if}}',
    '  <details class="sotl-card-details" open><summary>Scene Anchors</summary><ul class="sotl-anchors-list">{{#each anchors}}<li>{{.}}</li>{{/each}}</ul></details>',
    '  {{#if contradictions}}<details class="sotl-card-details"><summary>Contradictions</summary><ul class="sotl-anchors-list">{{#each contradictions}}<li>{{.}}</li>{{/each}}</ul></details>{{/if}}',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, a medium-detail story tracking system.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Balanced Story Loom schema exactly.',
    'Provide stable facts, tracking details, and active threads.',
    'Keep arrays capped. Empty strings and [] are used for unknown or empty blocks.',
  ].join('\n'),
  injectionTemplate: '[Balanced Story Loom]\n{{compactSummary}}',
  maxInjectionTokens: 400,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'normal',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'A shared secret in Lantern Hall',
    location: 'Lantern Hall',
    environment: 'Dimly lit, warm hearth, rain drumming on high windows',
    time: 'Late evening',
    mood: 'intimate but guarded',
    delta: 'Mira showed Josh the letter but refused to let him hold it.',
    cast: [
      {
        name: 'Mira',
        role: 'barkeep',
        position: 'by the fireplace',
        outfit: 'dark woolen coat, damp leather boots',
        emotion: 'hesitant',
        pockets: ['sealed letter'],
      },
      {
        name: 'Josh',
        role: 'guest',
        position: 'sitting on the rug',
        outfit: 'casual knits',
        emotion: 'curious',
        pockets: ['pocket knife'],
      },
    ],
    relationships: [
      { parties: 'Mira & Josh', tone: 'cautious trust', details: 'Mira shared the letter but is holding back its full history.' },
    ],
    inventory: ['sealed letter', 'brass key', 'pocket knife'],
    activeThread: 'Find out who wrote the letter.',
    anchors: ['The cellar door remains locked.', 'The storm outside is intensifying.'],
    contradictions: ['None.'],
  },
  createdAt: now,
  updatedAt: now,
};

// 4. Cast Continuity Loom Preset
export const castContinuityPreset: LoomPreset = {
  id: 'cast_continuity_loom',
  name: 'Cast Continuity Loom',
  version: '1.0.4',
  description: 'Focuses entirely on character consistency: posture, proximity, intent, and speech traits.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      cast: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            appearance: { type: 'string', default: '' },
            outfit: { type: 'string', default: '' },
            posture: { type: 'string', default: '' },
            proximity: { type: 'string', default: '' },
            hands: { type: 'string', default: '' },
            emotion: { type: 'string', default: '' },
            intent: { type: 'string', default: '' },
            dialogueColor: { type: 'string', default: '' },
            pockets: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
          },
        },
      },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">Cast Continuity Loom</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{time}}</span>',
    '  </header>',
    '  <p class="sotl-delta" style="margin-top: 6px;">📍 <strong>Location:</strong> {{location}}</p>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  <div class="sotl-section sotl-cast-section">',
    '    <h4>Character Continuities</h4>',
    '    <div style="display: grid; gap: 10px; margin-top: 6px;">',
    '      {{#each cast}}',
    '      <article class="sotl-panel" style="background: var(--lumiverse-fill-subtle, rgba(255,255,255,0.3)); padding: 10px; display: grid; gap: 4px;">',
    '        <h4 style="font-size: 13px; color: var(--lv-accent, #3864d9);">{{name}}</h4>',
    '        <div style="font-size: 12px; line-height: 1.4;">',
    '          <strong>Look:</strong> {{appearance}}<br>',
    '          <strong>Outfit:</strong> {{outfit}}<br>',
    '          <strong>Posture:</strong> {{posture}}<br>',
    '          <strong>Proximity:</strong> {{proximity}}<br>',
    '          <strong>Hands:</strong> {{hands}}<br>',
    '          <strong>Emotion:</strong> <em class="sotl-cast-emo">{{emotion}}</em><br>',
    '          <strong>Intent:</strong> {{intent}}<br>',
    '          <strong>Dialogue:</strong> <span style="font-style: italic;">{{dialogueColor}}</span>',
    '        </div>',
    '        {{#if pockets}}<div style="font-size: 11px; margin-top: 4px; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d));">🎒 Pockets: {{pockets}}</div>{{/if}}',
    '      </article>',
    '      {{/each}}',
    '    </div>',
    '  </div>',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, focusing entirely on roleplay character continuity details.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Cast Continuity Loom schema exactly.',
    'Document precise character appearances, outfits, gestures, distance, emotional states, goals, and dialogue details.',
    'Only record facts grounded in active dialogue and physical actions.',
  ].join('\n'),
  injectionTemplate: '[Cast Continuity Loom]\n{{compactSummary}}',
  maxInjectionTokens: 400,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'normal',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'Anxious alignment',
    location: 'Hallway entry',
    time: 'Sunset',
    delta: 'Mira crossed her arms tightly, avoiding Josh’s direct gaze.',
    cast: [
      {
        name: 'Mira',
        appearance: 'pale, brown hair tied back messily',
        outfit: 'damp green sweater',
        posture: 'arms crossed, shoulders hunched',
        proximity: 'two feet from door frame',
        hands: 'clutching her elbows',
        emotion: 'apprehensive',
        intent: 'deflect questions about the key',
        dialogueColor: 'hushed, clipped tone',
        pockets: ['brass key'],
      },
    ],
  },
  createdAt: now,
  updatedAt: now,
};

// 5. Full Continuity Ledger Preset
export const fullContinuityLedgerPreset: LoomPreset = {
  id: 'full_continuity_ledger',
  name: 'Full Continuity Ledger',
  version: '1.0.4',
  description: 'Largest preset tracking weather, lighting, secrets, relationships, meters, and anchors.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'weather', 'lighting', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      weather: { type: 'string', default: '' },
      lighting: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      cast: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            outfit: { type: 'string', default: '' },
            emotion: { type: 'string', default: '' },
            pockets: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
          },
        },
      },
      inventory: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      relationships: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            parties: { type: 'string', default: '' },
            status: { type: 'string', default: '' },
          },
        },
      },
      activeThread: { type: 'string', default: '' },
      secrets: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      rumors: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      anchors: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      contradictions: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      avoidNext: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      meters: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            value: { type: 'string', default: '' },
          },
        },
      },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">Full Continuity Ledger</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{mood}}</span>',
    '  </header>',
    '  <dl class="sotl-grid" style="grid-template-columns: repeat(3, 1fr); gap: 4px;">',
    '    <div class="sotl-grid-item"><dt>Location</dt><dd style="font-size: 11px;">{{location}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Time/Weather</dt><dd style="font-size: 11px;">{{time}} • {{weather}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Lighting</dt><dd style="font-size: 11px;">{{lighting}}</dd></div>',
    '  </dl>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  <div class="sotl-section sotl-cast-section">',
    '    <h4>Cast Continuity</h4>',
    '    <div class="sotl-cast-grid">',
    '      {{#each cast}}',
    '      <article class="sotl-cast-chip">',
    '        <strong>{{name}}</strong> <em class="sotl-cast-emo">({{emotion}})</em> <span style="font-size: 11px; margin-left: 4px;">👕 {{outfit}}</span>',
    '        {{#if pockets}}<span style="font-size: 10px; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d)); margin-left: 6px;">🎒 {{pockets}}</span>{{/if}}',
    '      </article>',
    '      {{/each}}',
    '    </div>',
    '  </div>',
    '  {{#if meters}}',
    '  <div style="margin-top: 8px;">',
    '    <h4 style="margin: 0 0 4px; font-size: 11px; text-transform: uppercase; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d));">Meters</h4>',
    '    <div style="display: flex; flex-wrap: wrap; gap: 6px;">',
    '      {{#each meters}}<span class="sotl-chip" style="background: rgba(220,10,10,0.06); border-color: rgba(220,10,10,0.15);">🔥 {{name}}: {{value}}</span>{{/each}}',
    '    </div>',
    '  </div>',
    '  {{/if}}',
    '  <details class="sotl-card-details" open><summary>Inventory & Relationships</summary>',
    '    <div style="font-size: 12px; margin-top: 4px;">',
    '      <strong>Inventory:</strong> {{inventory}}<br>',
    '      {{#each relationships}}<strong>{{parties}}</strong>: {{status}}<br>{{/each}}',
    '    </div>',
    '  </details>',
    '  <details class="sotl-card-details" open><summary>Story Continuum</summary>',
    '    <div style="font-size: 12px; line-height: 1.4; display: grid; gap: 4px;">',
    '      {{#if activeThread}}<div><strong>Active Thread:</strong> {{activeThread}}</div>{{/if}}',
    '      {{#if secrets}}<div><strong>Secrets:</strong> {{secrets}}</div>{{/if}}',
    '      {{#if rumors}}<div><strong>Rumors:</strong> {{rumors}}</div>{{/if}}',
    '      {{#if anchors}}<div><strong>Anchors:</strong> {{anchors}}</div>{{/if}}',
    '      {{#if contradictions}}<div><strong>Contradictions:</strong> {{contradictions}}</div>{{/if}}',
    '      {{#if avoidNext}}<div><strong>Avoid Next:</strong> {{avoidNext}}</div>{{/if}}',
    '    </div>',
    '  </details>',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, tracking full roleplay continuity details.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Full Continuity Ledger schema exactly.',
    'Preserve long-running secrets, rumors, active story arcs, lighting changes, weather state, and relationships.',
    'Keep arrays capped. Empty strings and [] are used for unknown or empty blocks.',
  ].join('\n'),
  injectionTemplate: '[Full Continuity Ledger]\n{{compactSummary}}',
  maxInjectionTokens: 450,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'normal',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'Storm over Ward House',
    location: 'Ward House Kitchen',
    time: '5:45 PM',
    weather: 'heavy rain, thunder',
    lighting: 'dim, flickering overhead fixture',
    mood: 'tense, electric',
    delta: 'Bridget’s sudden questioning spiked the tension in the room.',
    cast: [
      {
        name: 'Bridget Hanley',
        outfit: 'dark knit sweater',
        emotion: 'wryly curious',
        pockets: ['lighter'],
      },
      {
        name: 'Diane Ward',
        outfit: 'denim shorts, simple tee',
        emotion: 'tolerant but weary',
        pockets: ['keyring'],
      },
    ],
    inventory: ['letter', 'keyring', 'lighter'],
    relationships: [
      { parties: 'Bridget & Diane', status: 'playful tension' },
    ],
    activeThread: 'Resolve Marcus’s sudden absence.',
    secrets: ['Marcus left under threat.'],
    rumors: ['The cellar door leads to an old drainage system.'],
    anchors: ['The house is locked from inside.'],
    contradictions: ['None.'],
    avoidNext: ['Do not reveal Marcus’s whereabouts yet.'],
    meters: [
      { name: 'Tension', value: 'High' },
      { name: 'Rain intensity', value: 'Severe' },
    ],
  },
  createdAt: now,
  updatedAt: now,
};

// 6. Chronoscope Occult Ledger Preset
export const chronoscopeOccultLedgerPreset: LoomPreset = {
  id: 'chronoscope_occult_ledger',
  name: 'Chronoscope Occult Ledger',
  version: '1.0.25',
  description: 'A premium, highly-styled Gothic/Occult ledger with custom CSS, visual progress bars, and flexible tables.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      dangerLevel: { type: 'integer', default: 50 },
      aetherSanity: { type: 'integer', default: 80 },
      activeOmen: { type: 'string', default: '' },
      whispers: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      codexEntries: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            subject: { type: 'string', default: '' },
            notes: { type: 'string', default: '' },
            threat: { type: 'string', default: '' }
          }
        }
      }
    }
  },
  htmlTemplate: [
    '<div class="sotl-chronoscope sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <style>',
    '    .sotl-chronoscope {',
    '      font-family: \'Outfit\', \'Inter\', sans-serif;',
    '      background: linear-gradient(135deg, rgba(26, 15, 36, 0.95) 0%, rgba(12, 10, 20, 0.98) 100%);',
    '      border: 1px solid rgba(168, 85, 247, 0.4);',
    '      border-radius: 12px;',
    '      padding: 18px;',
    '      color: #e9d5ff;',
    '      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.6), inset 0 0 15px rgba(168, 85, 247, 0.1);',
    '    }',
    '    .sotl-ledger-header {',
    '      display: flex;',
    '      justify-content: space-between;',
    '      align-items: center;',
    '      border-bottom: 2px solid rgba(168, 85, 247, 0.25);',
    '      padding-bottom: 8px;',
    '      margin-bottom: 12px;',
    '    }',
    '    .sotl-ledger-title-group h3 {',
    '      font-size: 16px;',
    '      font-weight: 700;',
    '      color: #f3e8ff;',
    '      margin: 0;',
    '      letter-spacing: 0.5px;',
    '      text-shadow: 0 0 8px rgba(168, 85, 247, 0.4);',
    '    }',
    '    .sotl-ledger-subtitle {',
    '      font-size: 9px;',
    '      text-transform: uppercase;',
    '      color: #c084fc;',
    '      letter-spacing: 1.5px;',
    '      margin-top: 2px;',
    '    }',
    '    .sotl-ledger-mood-badge {',
    '      background: rgba(168, 85, 247, 0.2);',
    '      border: 1px solid rgba(168, 85, 247, 0.5);',
    '      color: #f3e8ff;',
    '      padding: 3px 8px;',
    '      border-radius: 9999px;',
    '      font-size: 11px;',
    '      font-weight: 500;',
    '    }',
    '    .sotl-ledger-stats-table {',
    '      width: 100%;',
    '      border-collapse: collapse;',
    '      margin-bottom: 12px;',
    '    }',
    '    .sotl-ledger-stats-table td {',
    '      padding: 6px;',
    '      vertical-align: middle;',
    '    }',
    '    .sotl-ledger-label {',
    '      font-size: 10px;',
    '      text-transform: uppercase;',
    '      color: #a78bfa;',
    '      letter-spacing: 0.5px;',
    '      width: 30%;',
    '    }',
    '    .sotl-ledger-value {',
    '      font-size: 12px;',
    '      color: #f3e8ff;',
    '      font-weight: 500;',
    '    }',
    '    .sotl-ledger-bar-container {',
    '      background: rgba(255, 255, 255, 0.05);',
    '      border-radius: 4px;',
    '      height: 8px;',
    '      overflow: hidden;',
    '      border: 1px solid rgba(168, 85, 247, 0.2);',
    '      position: relative;',
    '    }',
    '    .sotl-ledger-bar-fill-danger {',
    '      background: linear-gradient(90deg, #ef4444, #f43f5e);',
    '      height: 100%;',
    '      box-shadow: 0 0 6px rgba(239, 68, 68, 0.6);',
    '    }',
    '    .sotl-ledger-bar-fill-sanity {',
    '      background: linear-gradient(90deg, #3b82f6, #06b6d4);',
    '      height: 100%;',
    '      box-shadow: 0 0 6px rgba(59, 130, 246, 0.6);',
    '    }',
    '    .sotl-ledger-delta-box {',
    '      background: rgba(0, 0, 0, 0.2);',
    '      border-left: 3px solid #a855f7;',
    '      padding: 10px;',
    '      border-radius: 0 8px 8px 0;',
    '      margin-bottom: 12px;',
    '      font-size: 12px;',
    '      line-height: 1.5;',
    '      color: #f3e8ff;',
    '    }',
    '    .sotl-ledger-whispers-list {',
    '      margin: 0;',
    '      padding-left: 18px;',
    '      font-size: 11.5px;',
    '      color: #d8b4fe;',
    '      line-height: 1.5;',
    '    }',
    '    .sotl-ledger-codex-grid {',
    '      display: grid;',
    '      grid-template-columns: 1fr 1fr;',
    '      gap: 8px;',
    '      margin-top: 6px;',
    '    }',
    '    .sotl-ledger-codex-card {',
    '      background: rgba(168, 85, 247, 0.05);',
    '      border: 1px solid rgba(168, 85, 247, 0.2);',
    '      border-radius: 6px;',
    '      padding: 8px;',
    '    }',
    '    .sotl-ledger-codex-subject {',
    '      font-size: 11px;',
    '      font-weight: 700;',
    '      color: #f3e8ff;',
    '      margin-bottom: 2px;',
    '    }',
    '    .sotl-ledger-codex-notes {',
    '      font-size: 10.5px;',
    '      color: #c084fc;',
    '      margin-bottom: 4px;',
    '    }',
    '    .sotl-ledger-codex-threat {',
    '      font-size: 9px;',
    '      text-transform: uppercase;',
    '      font-weight: bold;',
    '      color: #ef4444;',
    '    }',
    '  </style>',
    '  <header class="sotl-ledger-header">',
    '    <div class="sotl-ledger-title-group">',
    '      <div class="sotl-ledger-subtitle">Chronoscope Occult Ledger</div>',
    '      <h3>{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-ledger-mood-badge">🔮 {{mood}}</span>',
    '  </header>',
    '  <table class="sotl-ledger-stats-table">',
    '    <tr>',
    '      <td class="sotl-ledger-label">📍 Location</td>',
    '      <td class="sotl-ledger-value" colspan="2">{{location}}</td>',
    '    </tr>',
    '    <tr>',
    '      <td class="sotl-ledger-label">⏳ Epoch / Time</td>',
    '      <td class="sotl-ledger-value" colspan="2">{{time}}</td>',
    '    </tr>',
    '    <tr>',
    '      <td class="sotl-ledger-label">🔥 Danger</td>',
    '      <td style="width: 50%;">',
    '        <div class="sotl-ledger-bar-container">',
    '          <div class="sotl-ledger-bar-fill-danger" style="width: {{dangerLevel}}%;"></div>',
    '        </div>',
    '      </td>',
    '      <td class="sotl-ledger-value" style="text-align: right; width: 20%;">{{dangerLevel}}%</td>',
    '    </tr>',
    '    <tr>',
    '      <td class="sotl-ledger-label">🌀 Sanity</td>',
    '      <td>',
    '        <div class="sotl-ledger-bar-container">',
    '          <div class="sotl-ledger-bar-fill-sanity" style="width: {{aetherSanity}}%;"></div>',
    '        </div>',
    '      </td>',
    '      <td class="sotl-ledger-value" style="text-align: right;">{{aetherSanity}}%</td>',
    '    </tr>',
    '    {{#if activeOmen}}',
    '    <tr>',
    '      <td class="sotl-ledger-label">💀 Omen</td>',
    '      <td class="sotl-ledger-value" colspan="2" style="color: #f43f5e; font-weight: 600;">{{activeOmen}}</td>',
    '    </tr>',
    '    {{/if}}',
    '  </table>',
    '  <div class="sotl-ledger-delta-box">{{delta}}</div>',
    '  {{#if whispers}}',
    '  <details class="sotl-card-details" open>',
    '    <summary style="font-size: 11px; text-transform: uppercase; color: #a78bfa; letter-spacing: 0.5px;">Whispers of the Loom</summary>',
    '    <ul class="sotl-ledger-whispers-list">',
    '      {{#each whispers}}<li>{{.}}</li>{{/each}}',
    '    </ul>',
    '  </details>',
    '  {{/if}}',
    '  {{#if codexEntries}}',
    '  <details class="sotl-card-details" open>',
    '    <summary style="font-size: 11px; text-transform: uppercase; color: #a78bfa; letter-spacing: 0.5px;">Active Codex Entities</summary>',
    '    <div class="sotl-ledger-codex-grid">',
    '      {{#each codexEntries}}',
    '      <div class="sotl-ledger-codex-card">',
    '        <div class="sotl-ledger-codex-subject">👤 {{subject}}</div>',
    '        <div class="sotl-ledger-codex-notes">{{notes}}</div>',
    '        {{#if threat}}<div class="sotl-ledger-codex-threat">⚠️ {{threat}}</div>{{/if}}',
    '      </div>',
    '      {{/each}}',
    '    </div>',
    '  </details>',
    '  {{/if}}',
    '</div>'
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, tracking the Gothic Chronoscope Occult continuity ledger details.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Chronoscope Occult Ledger schema exactly.',
    'Ensure you track the active location, time/epoch, mood, and delta.',
    'Compute dangerLevel (0 to 100) and aetherSanity (0 to 100) as whole integers reflecting current scene elements.',
    'Record whispers and active codex entry details if supernatural, cosmic, or threatening entities or facts are described.',
  ].join('\n'),
  injectionTemplate: '[Chronoscope Occult Ledger]\n{{compactSummary}}',
  maxInjectionTokens: 450,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'normal',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'A flicker in the dark vault',
    location: 'Catacomb Chamber VII',
    time: 'Midnight (The Third Watch)',
    mood: 'ominous and claustrophobic',
    delta: 'The high torch extinguished with a sudden hiss, leaving only an eerie crimson purple static from the central sarcophagus.',
    dangerLevel: 85,
    aetherSanity: 45,
    activeOmen: 'The Blood Moon rises behind the stained vault.',
    whispers: [
      'He who sleeps under the stone is dreaming of you.',
      'The static is growing louder by the minute.'
    ],
    codexEntries: [
      {
        subject: 'The Vault Keeper',
        notes: 'A tall skeletal apparition wearing decayed velvet robes and a brass chronoscope lens.',
        threat: 'High'
      }
    ],
  },
  createdAt: now,
  updatedAt: now,
};

export const builtInPresets: LoomPreset[] = [
  grandContinuityAtlasPreset,
  microLoomPreset,
  slimScenePreset,
  balancedStoryPreset,
  castContinuityPreset,
  fullContinuityLedgerPreset,
  chronoscopeOccultLedgerPreset,
];
