import type { LoomPreset, LoomSettings } from './types.js';

export const LOOM_VERSION = '1.0.11';
export const LOOM_SCHEMA_VERSION = '1';
export const SLIM_SCENE_PRESET_ID = 'slim_scene_loom';
export const STORAGE_KEYS = {
  settings: 'settings.json',
  presets: 'presets.json',
  trackerStates: 'tracker-states.json',
} as const;

const now = '2026-01-01T00:00:00.000Z';

export const defaultSettings: LoomSettings = {
  enabled: true,
  activePresetId: SLIM_SCENE_PRESET_ID,
  autoGenerate: false,
  useDefaultConnectionFallback: true,
  stripTrackerBlocksFromMessages: false,
  showFloatingButton: false,
  showMessageButtons: true,
  debugMode: false,
  promptInjectionEnabled: false,
  showChatHudLauncher: true,
  hudDefaultView: 'full',
  renderInMessages: false,
  messageCardPlacement: 'top',
  cardDensity: 'compact',
  trackerHistoryLimit: 5,
  sidecarGenerationTimeoutMs: 180000,
  useSafeRenderer: false,
};

// 1. Micro Loom Preset
export const microLoomPreset: LoomPreset = {
  id: 'micro_loom',
  name: 'Micro Loom',
  version: '1.0.0',
  description: 'Smallest, fastest tracker. Best for low token usage and fast models.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      cast: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      activeThread: { type: 'string', default: '' },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">Micro Loom</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{mood}}</span>',
    '  </header>',
    '  <dl class="sotl-grid">',
    '    <div class="sotl-grid-item"><dt>Location</dt><dd>{{location}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Time</dt><dd>{{time}}</dd></div>',
    '  </dl>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  <details class="sotl-card-details" open><summary>Cast Present</summary><ul class="sotl-anchors-list">{{#each cast}}<li>{{.}}</li>{{/each}}</ul></details>',
    '  {{#if activeThread}}<details class="sotl-card-details" open><summary>Active Thread</summary><p class="sotl-thread-desc">{{activeThread}}</p></details>{{/if}}',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, a micro-sized continuity tracker for an AI roleplay chat.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Micro Loom schema exactly.',
    'Preserve stable facts from the previous tracker unless the latest assistant message clearly changes them.',
    'Only update what changed this turn. Do not invent missing details.',
    'Use empty strings and [] for unknowns.',
    'Keep cast array under 4 items.',
  ].join('\n'),
  injectionTemplate: '[Micro Loom]\n{{compactSummary}}',
  maxInjectionTokens: 150,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'compact',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'Quick word in the foyer',
    location: 'Foyer',
    time: 'Late evening',
    mood: 'tense',
    delta: 'Mira entered quietly without shaking off her wet coat.',
    cast: ['Mira', 'Josh'],
    activeThread: 'Learn what Mira is hiding.',
  },
  createdAt: now,
  updatedAt: now,
};

// 2. Slim Scene Loom (Polished current preset)
export const slimSceneSampleData: Record<string, unknown> = {
  schemaVersion: LOOM_SCHEMA_VERSION,
  sceneTitle: 'A quiet turn in the old hall',
  location: 'Lantern Hall',
  time: 'Late evening',
  mood: 'watchful',
  delta: 'Mira noticed the sealed letter and did not comment on it.',
  showCast: true,
  cast: [
    {
      name: 'Mira',
      role: 'barkeep',
      position: 'behind the counter',
      outfit: 'rolled sleeves, dark apron',
      emotion: 'guarded',
      inventory: ['sealed letter'],
    },
  ],
  showInventory: true,
  inventory: ['sealed letter', 'brass key'],
  showThreads: true,
  activeThread: 'Find out who left the letter.',
  anchors: ['The cellar door is locked.', 'Rain is getting heavier outside.'],
  avoidNext: ['Do not reveal the letter contents yet.'],
};

export const slimScenePreset: LoomPreset = {
  id: SLIM_SCENE_PRESET_ID,
  name: 'Slim Scene Loom',
  version: '1.0.0',
  description: 'A low-token continuity tracker for location, cast, mood, inventory, deltas, and active story anchors.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      showCast: { type: 'boolean', default: false },
      cast: {
        type: 'array',
        maxItems: 6,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            role: { type: 'string', default: '' },
            position: { type: 'string', default: '' },
            outfit: { type: 'string', default: '' },
            emotion: { type: 'string', default: '' },
            inventory: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
          },
        },
      },
      showInventory: { type: 'boolean', default: false },
      inventory: { type: 'array', maxItems: 8, default: [], items: { type: 'string' } },
      showThreads: { type: 'boolean', default: false },
      activeThread: { type: 'string', default: '' },
      anchors: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      avoidNext: { type: 'array', maxItems: 5, default: [], items: { type: 'string' } },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">State of the Loom</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{mood}}</span>',
    '  </header>',
    '  <dl class="sotl-grid">',
    '    <div class="sotl-grid-item"><dt>Location</dt><dd>{{location}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Time</dt><dd>{{time}}</dd></div>',
    '  </dl>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  {{#if showCast}}<div class="sotl-section sotl-cast-section"><h4>Cast Members</h4><div class="sotl-cast-grid">{{#each cast}}<article class="sotl-cast-chip"><strong>{{name}}</strong> <span class="sotl-cast-role">{{role}}</span> <span class="sotl-cast-pos">{{position}}</span> <em class="sotl-cast-emo">{{emotion}}</em></article>{{/each}}</div></div>{{/if}}',
    '  {{#if showInventory}}<details class="sotl-card-details" open><summary>Inventory Items</summary><ul class="sotl-inventory-list">{{#each inventory}}<li>{{.}}</li>{{/each}}</ul></details>{{/if}}',
    '  {{#if showThreads}}<details class="sotl-card-details" open><summary>Active Thread</summary><p class="sotl-thread-desc">{{activeThread}}</p></details>{{/if}}',
    '  <details class="sotl-card-details" open><summary>Scene Anchors</summary><ul class="sotl-anchors-list">{{#each anchors}}<li>{{.}}</li>{{/each}}</ul></details>',
    '  <details class="sotl-card-details"><summary>Avoid Next (Instructions)</summary><ul class="sotl-avoid-list">{{#each avoidNext}}<li>{{.}}</li>{{/each}}</ul></details>',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, a continuity tracker for an AI roleplay chat.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Slim Scene Loom schema exactly.',
    'Preserve stable facts from the previous tracker unless the latest assistant message clearly changes them.',
    'Only update what changed this turn. Do not invent missing details.',
    'Use empty strings, false, 0, and [] for unknowns.',
    'Keep arrays within their maxItems caps.',
  ].join('\n'),
  injectionTemplate: '[State of the Loom placeholder]\n{{compactSummary}}',
  maxInjectionTokens: 350,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'compact',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: slimSceneSampleData,
  createdAt: now,
  updatedAt: now,
};

// 3. Balanced Story Loom Preset
export const balancedStoryPreset: LoomPreset = {
  id: 'balanced_story_loom',
  name: 'Balanced Story Loom',
  version: '1.0.0',
  description: 'Medium-detail continuity tracker. Monitors environment, relationships, and cast pockets.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'environment', 'time', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      environment: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      cast: {
        type: 'array',
        maxItems: 5,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            role: { type: 'string', default: '' },
            position: { type: 'string', default: '' },
            outfit: { type: 'string', default: '' },
            emotion: { type: 'string', default: '' },
            pockets: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
          },
        },
      },
      relationships: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            parties: { type: 'string', default: '' },
            tone: { type: 'string', default: '' },
            details: { type: 'string', default: '' },
          },
        },
      },
      inventory: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      activeThread: { type: 'string', default: '' },
      anchors: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      contradictions: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">Balanced Story Loom</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{mood}}</span>',
    '  </header>',
    '  <p class="sotl-delta" style="font-size: 11px; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d)); margin-bottom: 8px;"><strong>Environment:</strong> {{environment}}</p>',
    '  <dl class="sotl-grid">',
    '    <div class="sotl-grid-item"><dt>Location</dt><dd>{{location}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Time</dt><dd>{{time}}</dd></div>',
    '  </dl>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  <div class="sotl-section sotl-cast-section">',
    '    <h4>Cast Details</h4>',
    '    <div class="sotl-cast-grid">',
    '      {{#each cast}}',
    '      <article class="sotl-cast-chip" style="flex-direction: column; align-items: flex-start; gap: 2px;">',
    '        <div><strong>{{name}}</strong> <span class="sotl-cast-role">({{role}})</span></div>',
    '        <div style="font-size: 11px;">📍 {{position}} • 👕 {{outfit}}</div>',
    '        <div style="font-size: 11px;">🎭 <em class="sotl-cast-emo">{{emotion}}</em></div>',
    '        {{#if pockets}}<div style="font-size: 10px; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d));">🎒 Pockets: {{pockets}}</div>{{/if}}',
    '      </article>',
    '      {{/each}}',
    '    </div>',
    '  </div>',
    '  {{#if relationships}}',
    '  <details class="sotl-card-details" open><summary>Relationships</summary>',
    '    <ul class="sotl-anchors-list">',
    '      {{#each relationships}}',
    '      <li><strong>{{parties}}</strong>: <em>{{tone}}</em> — {{details}}</li>',
    '      {{/each}}',
    '    </ul>',
    '  </details>',
    '  {{/if}}',
    '  <details class="sotl-card-details"><summary>Inventory Items</summary><ul class="sotl-inventory-list">{{#each inventory}}<li>{{.}}</li>{{/each}}</ul></details>',
    '  {{#if activeThread}}<details class="sotl-card-details" open><summary>Active Thread</summary><p class="sotl-thread-desc">{{activeThread}}</p></details>{{/if}}',
    '  <details class="sotl-card-details" open><summary>Scene Anchors</summary><ul class="sotl-anchors-list">{{#each anchors}}<li>{{.}}</li>{{/each}}</ul></details>',
    '  {{#if contradictions}}<details class="sotl-card-details"><summary>Contradictions</summary><ul class="sotl-anchors-list">{{#each contradictions}}<li>{{.}}</li>{{/each}}</ul></details>{{/if}}',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, a medium-detail story tracking system.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Balanced Story Loom schema exactly.',
    'Provide stable facts, tracking details, and active threads.',
    'Keep arrays capped. Empty strings and [] are used for unknown or empty blocks.',
  ].join('\n'),
  injectionTemplate: '[Balanced Story Loom]\n{{compactSummary}}',
  maxInjectionTokens: 400,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'normal',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'A shared secret in Lantern Hall',
    location: 'Lantern Hall',
    environment: 'Dimly lit, warm hearth, rain drumming on high windows',
    time: 'Late evening',
    mood: 'intimate but guarded',
    delta: 'Mira showed Josh the letter but refused to let him hold it.',
    cast: [
      {
        name: 'Mira',
        role: 'barkeep',
        position: 'by the fireplace',
        outfit: 'dark woolen coat, damp leather boots',
        emotion: 'hesitant',
        pockets: ['sealed letter'],
      },
      {
        name: 'Josh',
        role: 'guest',
        position: 'sitting on the rug',
        outfit: 'casual knits',
        emotion: 'curious',
        pockets: ['pocket knife'],
      },
    ],
    relationships: [
      { parties: 'Mira & Josh', tone: 'cautious trust', details: 'Mira shared the letter but is holding back its full history.' },
    ],
    inventory: ['sealed letter', 'brass key', 'pocket knife'],
    activeThread: 'Find out who wrote the letter.',
    anchors: ['The cellar door remains locked.', 'The storm outside is intensifying.'],
    contradictions: ['None.'],
  },
  createdAt: now,
  updatedAt: now,
};

// 4. Cast Continuity Loom Preset
export const castContinuityPreset: LoomPreset = {
  id: 'cast_continuity_loom',
  name: 'Cast Continuity Loom',
  version: '1.0.0',
  description: 'Focuses entirely on character consistency: posture, proximity, intent, and speech traits.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      cast: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            appearance: { type: 'string', default: '' },
            outfit: { type: 'string', default: '' },
            posture: { type: 'string', default: '' },
            proximity: { type: 'string', default: '' },
            hands: { type: 'string', default: '' },
            emotion: { type: 'string', default: '' },
            intent: { type: 'string', default: '' },
            dialogueColor: { type: 'string', default: '' },
            pockets: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
          },
        },
      },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">Cast Continuity Loom</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{time}}</span>',
    '  </header>',
    '  <p class="sotl-delta" style="margin-top: 6px;">📍 <strong>Location:</strong> {{location}}</p>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  <div class="sotl-section sotl-cast-section">',
    '    <h4>Character Continuities</h4>',
    '    <div style="display: grid; gap: 10px; margin-top: 6px;">',
    '      {{#each cast}}',
    '      <article class="sotl-panel" style="background: var(--lumiverse-fill-subtle, rgba(255,255,255,0.3)); padding: 10px; display: grid; gap: 4px;">',
    '        <h4 style="font-size: 13px; color: var(--lv-accent, #3864d9);">{{name}}</h4>',
    '        <div style="font-size: 12px; line-height: 1.4;">',
    '          <strong>Look:</strong> {{appearance}}<br>',
    '          <strong>Outfit:</strong> {{outfit}}<br>',
    '          <strong>Posture:</strong> {{posture}}<br>',
    '          <strong>Proximity:</strong> {{proximity}}<br>',
    '          <strong>Hands:</strong> {{hands}}<br>',
    '          <strong>Emotion:</strong> <em class="sotl-cast-emo">{{emotion}}</em><br>',
    '          <strong>Intent:</strong> {{intent}}<br>',
    '          <strong>Dialogue:</strong> <span style="font-style: italic;">{{dialogueColor}}</span>',
    '        </div>',
    '        {{#if pockets}}<div style="font-size: 11px; margin-top: 4px; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d));">🎒 Pockets: {{pockets}}</div>{{/if}}',
    '      </article>',
    '      {{/each}}',
    '    </div>',
    '  </div>',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, focusing entirely on roleplay character continuity details.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Cast Continuity Loom schema exactly.',
    'Document precise character appearances, outfits, gestures, distance, emotional states, goals, and dialogue details.',
    'Only record facts grounded in active dialogue and physical actions.',
  ].join('\n'),
  injectionTemplate: '[Cast Continuity Loom]\n{{compactSummary}}',
  maxInjectionTokens: 400,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'normal',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'Anxious alignment',
    location: 'Hallway entry',
    time: 'Sunset',
    delta: 'Mira crossed her arms tightly, avoiding Josh’s direct gaze.',
    cast: [
      {
        name: 'Mira',
        appearance: 'pale, brown hair tied back messily',
        outfit: 'damp green sweater',
        posture: 'arms crossed, shoulders hunched',
        proximity: 'two feet from door frame',
        hands: 'clutching her elbows',
        emotion: 'apprehensive',
        intent: 'deflect questions about the key',
        dialogueColor: 'hushed, clipped tone',
        pockets: ['brass key'],
      },
    ],
  },
  createdAt: now,
  updatedAt: now,
};

// 5. Full Continuity Ledger Preset
export const fullContinuityLedgerPreset: LoomPreset = {
  id: 'full_continuity_ledger',
  name: 'Full Continuity Ledger',
  version: '1.0.0',
  description: 'Largest preset tracking weather, lighting, secrets, relationships, meters, and anchors.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'weather', 'lighting', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      weather: { type: 'string', default: '' },
      lighting: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      cast: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            outfit: { type: 'string', default: '' },
            emotion: { type: 'string', default: '' },
            pockets: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
          },
        },
      },
      inventory: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      relationships: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            parties: { type: 'string', default: '' },
            status: { type: 'string', default: '' },
          },
        },
      },
      activeThread: { type: 'string', default: '' },
      secrets: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      rumors: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      anchors: { type: 'array', maxItems: 6, default: [], items: { type: 'string' } },
      contradictions: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      avoidNext: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      meters: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', default: '' },
            value: { type: 'string', default: '' },
          },
        },
      },
    },
  },
  htmlTemplate: [
    '<section class="sotl-card sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <header class="sotl-card__head">',
    '    <div class="sotl-card__header-main">',
    '      <div class="sotl-card__eyebrow">Full Continuity Ledger</div>',
    '      <h3 class="sotl-card__title">{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-pill sotl-pill--mood">{{mood}}</span>',
    '  </header>',
    '  <dl class="sotl-grid" style="grid-template-columns: repeat(3, 1fr); gap: 4px;">',
    '    <div class="sotl-grid-item"><dt>Location</dt><dd style="font-size: 11px;">{{location}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Time/Weather</dt><dd style="font-size: 11px;">{{time}} • {{weather}}</dd></div>',
    '    <div class="sotl-grid-item"><dt>Lighting</dt><dd style="font-size: 11px;">{{lighting}}</dd></div>',
    '  </dl>',
    '  <p class="sotl-delta">{{delta}}</p>',
    '  <div class="sotl-section sotl-cast-section">',
    '    <h4>Cast Continuity</h4>',
    '    <div class="sotl-cast-grid">',
    '      {{#each cast}}',
    '      <article class="sotl-cast-chip">',
    '        <strong>{{name}}</strong> <em class="sotl-cast-emo">({{emotion}})</em> <span style="font-size: 11px; margin-left: 4px;">👕 {{outfit}}</span>',
    '        {{#if pockets}}<span style="font-size: 10px; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d)); margin-left: 6px;">🎒 {{pockets}}</span>{{/if}}',
    '      </article>',
    '      {{/each}}',
    '    </div>',
    '  </div>',
    '  {{#if meters}}',
    '  <div style="margin-top: 8px;">',
    '    <h4 style="margin: 0 0 4px; font-size: 11px; text-transform: uppercase; color: var(--lumiverse-text-muted, var(--lv-text-muted, #64707d));">Meters</h4>',
    '    <div style="display: flex; flex-wrap: wrap; gap: 6px;">',
    '      {{#each meters}}<span class="sotl-chip" style="background: rgba(220,10,10,0.06); border-color: rgba(220,10,10,0.15);">🔥 {{name}}: {{value}}</span>{{/each}}',
    '    </div>',
    '  </div>',
    '  {{/if}}',
    '  <details class="sotl-card-details" open><summary>Inventory & Relationships</summary>',
    '    <div style="font-size: 12px; margin-top: 4px;">',
    '      <strong>Inventory:</strong> {{inventory}}<br>',
    '      {{#each relationships}}<strong>{{parties}}</strong>: {{status}}<br>{{/each}}',
    '    </div>',
    '  </details>',
    '  <details class="sotl-card-details" open><summary>Story Continuum</summary>',
    '    <div style="font-size: 12px; line-height: 1.4; display: grid; gap: 4px;">',
    '      {{#if activeThread}}<div><strong>Active Thread:</strong> {{activeThread}}</div>{{/if}}',
    '      {{#if secrets}}<div><strong>Secrets:</strong> {{secrets}}</div>{{/if}}',
    '      {{#if rumors}}<div><strong>Rumors:</strong> {{rumors}}</div>{{/if}}',
    '      {{#if anchors}}<div><strong>Anchors:</strong> {{anchors}}</div>{{/if}}',
    '      {{#if contradictions}}<div><strong>Contradictions:</strong> {{contradictions}}</div>{{/if}}',
    '      {{#if avoidNext}}<div><strong>Avoid Next:</strong> {{avoidNext}}</div>{{/if}}',
    '    </div>',
    '  </details>',
    '</section>',
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, tracking full roleplay continuity details.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Full Continuity Ledger schema exactly.',
    'Preserve long-running secrets, rumors, active story arcs, lighting changes, weather state, and relationships.',
    'Keep arrays capped. Empty strings and [] are used for unknown or empty blocks.',
  ].join('\n'),
  injectionTemplate: '[Full Continuity Ledger]\n{{compactSummary}}',
  maxInjectionTokens: 450,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'normal',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'Storm over Ward House',
    location: 'Ward House Kitchen',
    time: '5:45 PM',
    weather: 'heavy rain, thunder',
    lighting: 'dim, flickering overhead fixture',
    mood: 'tense, electric',
    delta: 'Bridget’s sudden questioning spiked the tension in the room.',
    cast: [
      {
        name: 'Bridget Hanley',
        outfit: 'dark knit sweater',
        emotion: 'wryly curious',
        pockets: ['lighter'],
      },
      {
        name: 'Diane Ward',
        outfit: 'denim shorts, simple tee',
        emotion: 'tolerant but weary',
        pockets: ['keyring'],
      },
    ],
    inventory: ['letter', 'keyring', 'lighter'],
    relationships: [
      { parties: 'Bridget & Diane', status: 'playful tension' },
    ],
    activeThread: 'Resolve Marcus’s sudden absence.',
    secrets: ['Marcus left under threat.'],
    rumors: ['The cellar door leads to an old drainage system.'],
    anchors: ['The house is locked from inside.'],
    contradictions: ['None.'],
    avoidNext: ['Do not reveal Marcus’s whereabouts yet.'],
    meters: [
      { name: 'Tension', value: 'High' },
      { name: 'Rain intensity', value: 'Severe' },
    ],
  },
  createdAt: now,
  updatedAt: now,
};

// 6. Chronoscope Occult Ledger Preset
export const chronoscopeOccultLedgerPreset: LoomPreset = {
  id: 'chronoscope_occult_ledger',
  name: 'Chronoscope Occult Ledger',
  version: '1.0.11',
  description: 'A premium, highly-styled Gothic/Occult ledger with custom CSS, visual progress bars, and flexible tables.',
  mode: 'hybrid',
  schemaJson: {
    type: 'object',
    required: ['schemaVersion', 'sceneTitle', 'location', 'time', 'mood', 'delta'],
    properties: {
      schemaVersion: { type: 'string', default: LOOM_SCHEMA_VERSION },
      sceneTitle: { type: 'string', default: '' },
      location: { type: 'string', default: '' },
      time: { type: 'string', default: '' },
      mood: { type: 'string', default: '' },
      delta: { type: 'string', default: '' },
      dangerLevel: { type: 'integer', default: 50 },
      aetherSanity: { type: 'integer', default: 80 },
      activeOmen: { type: 'string', default: '' },
      whispers: { type: 'array', maxItems: 4, default: [], items: { type: 'string' } },
      codexEntries: {
        type: 'array',
        maxItems: 4,
        default: [],
        items: {
          type: 'object',
          properties: {
            subject: { type: 'string', default: '' },
            notes: { type: 'string', default: '' },
            threat: { type: 'string', default: '' }
          }
        }
      }
    }
  },
  htmlTemplate: [
    '<div class="sotl-chronoscope sotl-density-{{density}} sotl-theme-{{theme}}" data-sotl-card="true">',
    '  <style>',
    '    .sotl-chronoscope {',
    '      font-family: \'Outfit\', \'Inter\', sans-serif;',
    '      background: linear-gradient(135deg, rgba(26, 15, 36, 0.95) 0%, rgba(12, 10, 20, 0.98) 100%);',
    '      border: 1px solid rgba(168, 85, 247, 0.4);',
    '      border-radius: 12px;',
    '      padding: 18px;',
    '      color: #e9d5ff;',
    '      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.6), inset 0 0 15px rgba(168, 85, 247, 0.1);',
    '    }',
    '    .sotl-ledger-header {',
    '      display: flex;',
    '      justify-content: space-between;',
    '      align-items: center;',
    '      border-bottom: 2px solid rgba(168, 85, 247, 0.25);',
    '      padding-bottom: 8px;',
    '      margin-bottom: 12px;',
    '    }',
    '    .sotl-ledger-title-group h3 {',
    '      font-size: 16px;',
    '      font-weight: 700;',
    '      color: #f3e8ff;',
    '      margin: 0;',
    '      letter-spacing: 0.5px;',
    '      text-shadow: 0 0 8px rgba(168, 85, 247, 0.4);',
    '    }',
    '    .sotl-ledger-subtitle {',
    '      font-size: 9px;',
    '      text-transform: uppercase;',
    '      color: #c084fc;',
    '      letter-spacing: 1.5px;',
    '      margin-top: 2px;',
    '    }',
    '    .sotl-ledger-mood-badge {',
    '      background: rgba(168, 85, 247, 0.2);',
    '      border: 1px solid rgba(168, 85, 247, 0.5);',
    '      color: #f3e8ff;',
    '      padding: 3px 8px;',
    '      border-radius: 9999px;',
    '      font-size: 11px;',
    '      font-weight: 500;',
    '    }',
    '    .sotl-ledger-stats-table {',
    '      width: 100%;',
    '      border-collapse: collapse;',
    '      margin-bottom: 12px;',
    '    }',
    '    .sotl-ledger-stats-table td {',
    '      padding: 6px;',
    '      vertical-align: middle;',
    '    }',
    '    .sotl-ledger-label {',
    '      font-size: 10px;',
    '      text-transform: uppercase;',
    '      color: #a78bfa;',
    '      letter-spacing: 0.5px;',
    '      width: 30%;',
    '    }',
    '    .sotl-ledger-value {',
    '      font-size: 12px;',
    '      color: #f3e8ff;',
    '      font-weight: 500;',
    '    }',
    '    .sotl-ledger-bar-container {',
    '      background: rgba(255, 255, 255, 0.05);',
    '      border-radius: 4px;',
    '      height: 8px;',
    '      overflow: hidden;',
    '      border: 1px solid rgba(168, 85, 247, 0.2);',
    '      position: relative;',
    '    }',
    '    .sotl-ledger-bar-fill-danger {',
    '      background: linear-gradient(90deg, #ef4444, #f43f5e);',
    '      height: 100%;',
    '      box-shadow: 0 0 6px rgba(239, 68, 68, 0.6);',
    '    }',
    '    .sotl-ledger-bar-fill-sanity {',
    '      background: linear-gradient(90deg, #3b82f6, #06b6d4);',
    '      height: 100%;',
    '      box-shadow: 0 0 6px rgba(59, 130, 246, 0.6);',
    '    }',
    '    .sotl-ledger-delta-box {',
    '      background: rgba(0, 0, 0, 0.2);',
    '      border-left: 3px solid #a855f7;',
    '      padding: 10px;',
    '      border-radius: 0 8px 8px 0;',
    '      margin-bottom: 12px;',
    '      font-size: 12px;',
    '      line-height: 1.5;',
    '      color: #f3e8ff;',
    '    }',
    '    .sotl-ledger-whispers-list {',
    '      margin: 0;',
    '      padding-left: 18px;',
    '      font-size: 11.5px;',
    '      color: #d8b4fe;',
    '      line-height: 1.5;',
    '    }',
    '    .sotl-ledger-codex-grid {',
    '      display: grid;',
    '      grid-template-columns: 1fr 1fr;',
    '      gap: 8px;',
    '      margin-top: 6px;',
    '    }',
    '    .sotl-ledger-codex-card {',
    '      background: rgba(168, 85, 247, 0.05);',
    '      border: 1px solid rgba(168, 85, 247, 0.2);',
    '      border-radius: 6px;',
    '      padding: 8px;',
    '    }',
    '    .sotl-ledger-codex-subject {',
    '      font-size: 11px;',
    '      font-weight: 700;',
    '      color: #f3e8ff;',
    '      margin-bottom: 2px;',
    '    }',
    '    .sotl-ledger-codex-notes {',
    '      font-size: 10.5px;',
    '      color: #c084fc;',
    '      margin-bottom: 4px;',
    '    }',
    '    .sotl-ledger-codex-threat {',
    '      font-size: 9px;',
    '      text-transform: uppercase;',
    '      font-weight: bold;',
    '      color: #ef4444;',
    '    }',
    '  </style>',
    '  <header class="sotl-ledger-header">',
    '    <div class="sotl-ledger-title-group">',
    '      <div class="sotl-ledger-subtitle">Chronoscope Occult Ledger</div>',
    '      <h3>{{sceneTitle}}</h3>',
    '    </div>',
    '    <span class="sotl-ledger-mood-badge">🔮 {{mood}}</span>',
    '  </header>',
    '  <table class="sotl-ledger-stats-table">',
    '    <tr>',
    '      <td class="sotl-ledger-label">📍 Location</td>',
    '      <td class="sotl-ledger-value" colspan="2">{{location}}</td>',
    '    </tr>',
    '    <tr>',
    '      <td class="sotl-ledger-label">⏳ Epoch / Time</td>',
    '      <td class="sotl-ledger-value" colspan="2">{{time}}</td>',
    '    </tr>',
    '    <tr>',
    '      <td class="sotl-ledger-label">🔥 Danger</td>',
    '      <td style="width: 50%;">',
    '        <div class="sotl-ledger-bar-container">',
    '          <div class="sotl-ledger-bar-fill-danger" style="width: {{dangerLevel}}%;"></div>',
    '        </div>',
    '      </td>',
    '      <td class="sotl-ledger-value" style="text-align: right; width: 20%;">{{dangerLevel}}%</td>',
    '    </tr>',
    '    <tr>',
    '      <td class="sotl-ledger-label">🌀 Sanity</td>',
    '      <td>',
    '        <div class="sotl-ledger-bar-container">',
    '          <div class="sotl-ledger-bar-fill-sanity" style="width: {{aetherSanity}}%;"></div>',
    '        </div>',
    '      </td>',
    '      <td class="sotl-ledger-value" style="text-align: right;">{{aetherSanity}}%</td>',
    '    </tr>',
    '    {{#if activeOmen}}',
    '    <tr>',
    '      <td class="sotl-ledger-label">💀 Omen</td>',
    '      <td class="sotl-ledger-value" colspan="2" style="color: #f43f5e; font-weight: 600;">{{activeOmen}}</td>',
    '    </tr>',
    '    {{/if}}',
    '  </table>',
    '  <div class="sotl-ledger-delta-box">{{delta}}</div>',
    '  {{#if whispers}}',
    '  <details class="sotl-card-details" open>',
    '    <summary style="font-size: 11px; text-transform: uppercase; color: #a78bfa; letter-spacing: 0.5px;">Whispers of the Loom</summary>',
    '    <ul class="sotl-ledger-whispers-list">',
    '      {{#each whispers}}<li>{{.}}</li>{{/each}}',
    '    </ul>',
    '  </details>',
    '  {{/if}}',
    '  {{#if codexEntries}}',
    '  <details class="sotl-card-details" open>',
    '    <summary style="font-size: 11px; text-transform: uppercase; color: #a78bfa; letter-spacing: 0.5px;">Active Codex Entities</summary>',
    '    <div class="sotl-ledger-codex-grid">',
    '      {{#each codexEntries}}',
    '      <div class="sotl-ledger-codex-card">',
    '        <div class="sotl-ledger-codex-subject">👤 {{subject}}</div>',
    '        <div class="sotl-ledger-codex-notes">{{notes}}</div>',
    '        {{#if threat}}<div class="sotl-ledger-codex-threat">⚠️ {{threat}}</div>{{/if}}',
    '      </div>',
    '      {{/each}}',
    '    </div>',
    '  </details>',
    '  {{/if}}',
    '</div>'
  ].join(''),
  promptInstructions: [
    'You are State of the Loom, tracking the Gothic Chronoscope Occult continuity ledger details.',
    'Return valid JSON only. Do not use markdown fences.',
    'Use the Chronoscope Occult Ledger schema exactly.',
    'Ensure you track the active location, time/epoch, mood, and delta.',
    'Compute dangerLevel (0 to 100) and aetherSanity (0 to 100) as whole integers reflecting current scene elements.',
    'Record whispers and active codex entry details if supernatural, cosmic, or threatening entities or facts are described.',
  ].join('\n'),
  injectionTemplate: '[Chronoscope Occult Ledger]\n{{compactSummary}}',
  maxInjectionTokens: 450,
  defaultPlacement: 'top',
  renderOptions: {
    density: 'normal',
    theme: 'system',
    showControls: true,
  },
  parserOptions: {
    fenceNames: ['tracker', 'loom'],
    strictJson: true,
    repairInvalidJson: false,
  },
  sampleData: {
    schemaVersion: LOOM_SCHEMA_VERSION,
    sceneTitle: 'A flicker in the dark vault',
    location: 'Catacomb Chamber VII',
    time: 'Midnight (The Third Watch)',
    mood: 'ominous and claustrophobic',
    delta: 'The high torch extinguished with a sudden hiss, leaving only an eerie crimson purple static from the central sarcophagus.',
    dangerLevel: 85,
    aetherSanity: 45,
    activeOmen: 'The Blood Moon rises behind the stained vault.',
    whispers: [
      'He who sleeps under the stone is dreaming of you.',
      'The static is growing louder by the minute.'
    ],
    codexEntries: [
      {
        subject: 'The Vault Keeper',
        notes: 'A tall skeletal apparition wearing decayed velvet robes and a brass chronoscope lens.',
        threat: 'High'
      }
    ],
  },
  createdAt: now,
  updatedAt: now,
};

export const builtInPresets: LoomPreset[] = [
  microLoomPreset,
  slimScenePreset,
  balancedStoryPreset,
  castContinuityPreset,
  fullContinuityLedgerPreset,
  chronoscopeOccultLedgerPreset,
];
